const books=[
    {   id:"1",
        img:"https://m.media-amazon.com/images/I/711hfHGE+cL._AC_UL320_.jpg",
        title:"Great Stories for Children",
        author:"Ruskin Bond",
    },
    {   id:"2",
        img:"https://m.media-amazon.com/images/I/81YOuOGFCJL._AC_UL320_.jpg",
        title:"Harry Potter and the Philosopher's Stone",
        author:"J.K. Rowling",
    },
    {   id:"3",
        img:"https://m.media-amazon.com/images/I/91uHRqlDy3L._AC_UL320_.jpg",
        title:"101 Panchatantra Stories",
        author:"Dreamland Publications",
    },
    {   id:"4",
        img:"https://m.media-amazon.com/images/I/91sOjvWTmIL._RC%7C91sOjvWTmIL.jpg_SY300_SX300_.jpg",
        title:"A Brief History of Modern India ",
        author:"Spectrum Books ",
    },
    {   id:"5",
        img:"https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UL320_.jpg",
        title:"The Alchemist",
        author:"Paulo Coelho",
    },
    {   id:"6",
        img:"https://m.media-amazon.com/images/I/91AWwH8U3HS._AC_UL320_.jpg",
        title:"The Little Prince",
        author:"Antoine De Saint-Exupéry",
    },
    {   id:"7",
        img:"https://m.media-amazon.com/images/I/71JZ0neAP1L._AC_UL320_.jpg",
        title:"The Blue Umbrella",
        author:"Ruskin Bond",
    },
    {   id:"8",
        img:"https://m.media-amazon.com/images/I/81N1POIpxwL._AC_UL320_.jpg",
        title:"The Illustrated Stories Of Akbar and Birbal",
        author:" Wonder House Books",
    },
    {   id:"9",
        img:"https://m.media-amazon.com/images/I/91xAvyJmUUL._AC_UL320_.jpg",
        title:"Grandma's Bag of Stories: Collection of 20+ ",
        author:"Sudha Murty",
    }
]


export default books